; 来源: npm/README.md
; 功能: npm 用户级配置模板，使用时复制为 C:\Users\<用户>\.npmrc
; registry 为 npmmirror(淘宝镜像)加速下载; prefix/cache 自定义全局安装与缓存路径，按需修改盘符

prefix=E:\Develop\Node\global_modules\
cache=E:\Develop\Node\npm_cache\
registry=https://registry.npmmirror.com
