; 来源: npm/README.md
; 功能: pnpm rc 配置模板，自定义 store/cache/state/global 目录，按需修改盘符

store-dir=E:\Develop\Node\pnpm-store\store\
cache-dir=E:\Develop\Node\pnpm-store\cache\
state-dir=E:\Develop\Node\pnpm-store\state\
global-dir=E:\Develop\Node\pnpm-store\global\
